# Generated by Django 4.1.1 on 2022-09-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_email_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
    ]
