# Generated by Django 4.1.1 on 2022-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_company_alter_job_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
