# Generated by Django 4.1.1 on 2022-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_job_status_alter_job_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_url',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
    ]
