# Generated by Django 4.1.1 on 2022-09-11 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_job_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('due_date', models.DateField(default=None)),
                ('notes', models.TextField(default=None, max_length=500)),
                ('completed_status', models.BooleanField()),
                ('category', models.CharField(choices=[('Job-Specific CV', 'Job-Specific CV'), ('Job-Specific Resume', 'Job-Specific Resume'), ('Apply', 'Apply'), ('Follow Up', 'Follow Up'), ('Email: Response Required', 'Email: Response Required'), ('Call: Response Required', 'Call: Response Required'), ('Documents Requested: Response Required', 'Documents Requested: Response Required'), ('Phone Interview', 'Phone Interview'), ('Video Interview', 'Video Interview'), ('Technical Interview', 'Technical Interview'), ('On Site Interview', 'On Site Interview'), ('Follow Up: Thank You', 'Follow Up: Thank You'), ('Offer: Response Required', 'Offer: Response Required')], default=None, max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='jobs.job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
