# Generated by Django 4.1.1 on 2022-09-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Job-Specific CV', 'Job-Specific CV'), ('Job-Specific Resume', 'Job-Specific Resume'), ('Apply', 'Apply'), ('Follow Up', 'Follow Up'), ('Email: Response Required', 'Email: Response Required'), ('Call: Response Required', 'Call: Response Required'), ('Documents Requested: Response Required', 'Documents Requested: Response Required'), ('Phone Interview', 'Phone Interview'), ('Video Interview', 'Video Interview'), ('Technical Interview', 'Technical Interview'), ('On Site Interview', 'On Site Interview'), ('Follow Up: Thank You', 'Follow Up: Thank You'), ('Offer: Response Required', 'Offer: Response Required'), ('Other', 'Other')], default=None, max_length=100),
        ),
    ]
