# Generated by Django 4.1.1 on 2022-09-11 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_job_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('file_url', models.URLField(default=None)),
                ('category', models.CharField(choices=[('Resume', 'Resume'), ('CV', 'CV'), ('Cover Letter', 'Cover Letter'), ('Transcript', 'Transcript'), ('License', 'License'), ('Certification', 'Certification'), ('Writing Sample', 'Writing Sample'), ('Code Sample', 'Code Sample'), ('Offer Letter', 'Offer Letter'), ('Other', 'Other')], default=None, max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
