# Generated by Django 4.1.1 on 2022-09-11 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('industry', models.CharField(default=None, max_length=200)),
                ('founded', models.IntegerField()),
                ('hq_location', models.CharField(default=None, max_length=200)),
                ('size', models.CharField(default=None, max_length=200)),
                ('type', models.CharField(default=None, max_length=200)),
                ('specialties', models.TextField(default=None, max_length=500)),
                ('company_url', models.URLField(default=None)),
                ('description', models.TextField(default=None, max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
