# Generated by Django 4.1.1 on 2022-09-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_company_alter_job_benefits_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='jobs.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_url',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='hq_location',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='specialties',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
