# Generated by Django 4.1.1 on 2022-09-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_company_name'),
        ('companies', '0004_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='jobs.job'),
        ),
    ]
