# Generated by Django 4.1.1 on 2022-09-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_remove_company_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_url',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
    ]
