# Generated by Django 4.1.1 on 2022-09-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_company_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
